# Generated by Django 5.2.1 on 2025-05-30 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerprofile',
            name='address',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
